### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by mpicci** [dribnet/plat#2]
Hello
when I run plat sample --model celeba_64.discgen
I get this:

Loading DiscGenModel interface from discgen.interface
Loading model celeba_64.discgen
Traceback (most recent call last):
  File "/home/piccir/anaconda2/bin/plat", line 11, in <module>
    sys.exit(main())
  File "/home/piccir/anaconda2/lib/python2.7/site-packages/plat/bin/platcmd.py", line 12, in main
    handler.run()
  File "/home/piccir/anaconda2/lib/python2.7/site-packages/arghandler/base.py", line 295, in run
    self._subcommand_lookup[args.cmd](scmd_parser,context,args.cargs)
  File "/home/piccir/anaconda2/lib/python2.7/site-packages/plat/bin/sample.py", line 256, in sample
    run_with_args(args, dmodel, args.anchor_image, args.save_path, cur_z_step)
  File "/home/piccir/anaconda2/lib/python2.7/site-packages/plat/bin/sample.py", line 67, in run_with_args
    dmodel = zoo.load_model(args.model, args.model_file, args.model_type, args.model_interface)
  File "/home/piccir/anaconda2/lib/python2.7/site-packages/plat/zoo.py", line 72, in load_model
    return load_model_with_interface(model_file_name, model_interface)
  File "/home/piccir/anaconda2/lib/python2.7/site-packages/plat/zoo.py", line 50, in load_model_with_interface
    model = ModelClass(filename=model_file_name)
  File "/home/piccir/Documents/Repository/discgen/discgen/interface.py", line 60, in __init__
    self.model = Model(load(src).algorithm.cost)
  File "/home/piccir/anaconda2/lib/python2.7/site-packages/blocks/serialization.py", line 277, in load
    return p.load()
  File "/home/piccir/anaconda2/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/home/piccir/anaconda2/lib/python2.7/pickle.py", line 902, in load_binpersid
    self.append(self.persistent_load(pid))
  File "/home/piccir/anaconda2/lib/python2.7/site-packages/blocks/serialization.py", line 600, in __call__
    components = _unmangle_parameter_name(id_)
  File "/home/piccir/anaconda2/lib/python2.7/site-packages/blocks/serialization.py", line 633, in _unmangle_parameter_name
    return _INVERSE_ARRAY_TYPE_MAP[type_], context_name, name
KeyError: 'cuda_ndarray'

Any clue?
I reinstalled Theano with the version from the other issue

Thank you

**Comment by mpicci** [comment]
I solved the problem recompiling discgen,
sorry
